# Intentionally-bad Python. `ruff check` MUST fail here — that IS the test.
#
# Every finding below is deliberate and load-bearing, and the 13 selected rule
# families are ALL represented. If the count drops, the family that stopped
# firing is named in the diff rather than left as "something changed".
#
# If a finding stops firing, the config regressed: fix configs/python/ruff.toml,
# do NOT edit this file to make CI green (CLAUDE.md §5). The exact count is
# asserted in ci.yml.

# I001 — import block is unsorted and unformatted (typing before stdlib).
from typing import List  # UP035 — typing.List is deprecated on py312
import re
import asyncio
import os  # F401 — imported, never used


# N802 — function name should be lowercase.
def GetUser(items: list[str] = []) -> str:  # B006 — mutable default argument
    # S105 — hardcoded password assigned to a suspiciously-named variable.
    password = "hunter2"

    # W605 — invalid escape sequence; "\d" is not an escape, it is a latent bug
    # that only works by accident until the string is used somewhere stricter.
    digits = re.compile("\d+")

    # SIM108 — if/else block that is a ternary.
    if items:
        first = items[0]
    else:
        first = "none"

    # C401 — unnecessary generator, rewrite as a set comprehension.
    seen = set(c for c in first)

    # T201 — stray print(), the Python console.log.
    print(f"{password} {seen} {digits}")

    # E501 — line over the 100-character limit, which is the kind of line that turns a real diff unreadable.
    return first


async def load(path: str) -> List[str]:
    # ASYNC230 — blocking open() inside an async def blocks the whole loop.
    with open(path) as fh:
        return fh.readlines()


async def spawn() -> None:
    # RUF006 — the task is never stored, so it can be garbage-collected
    # mid-flight and the work silently vanishes.
    asyncio.create_task(load("data.txt"))
